# Generated by Django 4.1.5 on 2023-01-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name': 'Raca', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
