# Generated by Django 4.1.5 on 2023-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_alter_pet_options_alter_raca_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raca',
            options={'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
    ]
